const {chromium}=require(require('child_process').execSync('npm root -g').toString().trim()+'/playwright');
const {mock,seed}=require('/tmp/t/mock2.js');
(async()=>{const b=await chromium.launch();const c=await b.newContext({viewport:{width:390,height:800}});const p=await c.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));
await mock(p,{n:6});await p.addInitScript(s=>{try{if(!localStorage.getItem('folio'))localStorage.setItem('folio',JSON.stringify(s))}catch(e){}},seed(['Alpha','Beta']));
await p.addInitScript(()=>{window.__sh=[];navigator.share=async d=>{window.__sh.push(d)};});
await p.goto('file:///mnt/user-data/outputs/cypress.html');await p.waitForTimeout(2200);
const r=await p.evaluate(async()=>{const out={};let asked=0;const o=askBox;askBox=async x=>{asked++;return true};
 curA=Object.assign({},cur[0]);window.__sh.length=0;await doAct('share');out.reader=window.__sh.map(x=>x.url.slice(0,45));
 window.__sh.length=0;qaDo('share',0);await new Promise(r=>setTimeout(r,1200));out.card=window.__sh.map(x=>x.url.slice(0,45));out.asked=asked;
 out.menuHasPicture=/picture/i.test(mnMarkup());out.menuShare=(mnMarkup().match(/data-act="share">([^<]*)/)||[])[1];return out});
console.log(JSON.stringify(r),errs);await b.close()})();
